language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script:
  - "bundle exec rake lint spec SPEC_OPTS='--format documentation'"
sudo: false
env:
  - PUPPET_GEM_VERSION="~> 2.6.0"
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6.0"

notifications:
  email:
    - al@lab42.it
